var questions = [
    {"indice": 1, "question": "Quels sont les trois types de roches et comment se forment-elles?", "questionMemorisation": "Quel est le type de roches formées à partir de lave ou de magma solidifié?", "informationCle": "Roches ignées"},
    {"indice": 2, "question": "Quelles sont les étapes d’une éruption volcanique?", "questionMemorisation": "Nommez une étape de l’éruption volcanique qui précède l’étape de l’éruption.", "informationCle": "Accumulation du magma, montée du magma, pressurisation, fracturation"},
    {"indice": 3, "question": "Expliquez le principe de la photosynthèse et comment les plantes utilisent la lumière pour produire de l’énergie.", "questionMemorisation": "Dans le processus de photosynthèse, en quelle substance l’énergie lumineuse est-elle transformée?", "informationCle": "Glucose"},
    {"indice": 4, "question": "Expliquez le phénomène d’apparition d’un mirage supérieur et d’un mirage inférieur.", "questionMemorisation": "Quel type de mirage peut faire en sorte que des objets situés à l’horizon paraissent inversés?", "informationCle": "Mirage supérieur"},
    {"indice": 5, "question": "Comment se déroule le processus de transformation du sable en verre plat?", "questionMemorisation": "Lors de la transformation du sable, comment se nomme le procédé durant lequel le verre est étalé sur une surface liquide pour obtenir une épaisseur uniforme?", "informationCle": "Procédé de flottage"},
    {"indice": 6, "question": "Quelles sont les principales caractéristiques des étoiles de type O et quelles conséquences ont-elles sur leur cycle de vie?", "questionMemorisation": "Les étoiles de type O émettent une grande quantité de quel type de rayonnement?", "informationCle": "Ultraviolet"},
    {"indice": 7, "question": "Quels sont les éléments traditionnels caractéristiques d’un hanbok coréen et comment ces éléments varient-ils en fonction du genre?", "questionMemorisation": "Quel élément du hanbok est commun au costume féminin et au costume masculin?", "informationCle": "Veste/Jeogori"},
    {"indice": 8, "question": "Que raconte L’Avare de Molière?", "questionMemorisation": "Qui est Cléante par rapport à Harpagon, le personnage principal de la comédie L’Avare?", "informationCle": "Le fils d’Harpagon"},
    {"indice": 9, "question": "Quelles sont les différences entre l’anthropologie culturelle et l’anthropologie physique?", "questionMemorisation": "Quel type d’anthropologie s’intéresse entre autres aux langues et aux structures sociales?", "informationCle": "Anthropologie culturelle"},
    {"indice": 10, "question": "Quels sont les principaux secteurs économiques de l’Islande en dehors de l’industrie de la pêche, et comment contribuent-ils à l’économie du pays?", "questionMemorisation": "En Islande, la production de quel matériau constitue une activité économique importante?", "informationCle": "Aluminium"},
    {"indice": 11, "question": "Qu’est-ce qu’était l’apartheid en Afrique du Sud et que stipulait sa Pass Law?", "questionMemorisation": "Quelles étaient les conséquences infligées à un individu qui transgressait la Pass Law durant l’apartheid en Afrique du Sud?", "informationCle": "Arrestation, amendes ou emprisonnements"},
    {"indice": 12, "question": "Qu’est-ce que Motown Records et nommez 5 artistes interprètes qui y sont associés.", "questionMemorisation": "Nommez un artiste interprète phare du Motown.", "informationCle": "Michael Jackson, the Jackson Five, Diana Ross, The Supremes, The Four Tops, Martha and the Vandellas, Smokey Robinson, Gladys Knight, Marvin Gaye, Stevie Wonder, The Pointer Sisters, Edwin Starr, The Temptations, etc."},
    {"indice": 13, "question": "Quel est le cycle de vie d’une étoile?", "questionMemorisation": "Comment se nomme le type de nuage gigantesque de gaz et de poussières dans lequel les étoiles naissent?", "informationCle": "Nébuleuse"},
    {"indice": 14, "question": "Qu’est-ce que l’Expo 67 et comment les structures construites pour cette dernière sont actuellement utilisées?", "questionMemorisation": "Après l’Expo 67, en quoi a été rénové le pavillon de la France?", "informationCle": "Casino de Montréal"},
    {"indice": 15, "question": "Quels sont les principaux enjeux environnementaux pour les tortues de mer?", "questionMemorisation": "Nommez une activité humaine ayant un impact écologique négatif pour les tortues de mer.", "informationCle": "Capture accidentelle, perte et dégradation de l’habitat, chasse et braconnage, changement climatiques, pollution, maladies, l’empêtrement, consommation, etc."},
    {"indice": 16, "question": "Comment les zostères peuvent-elles être utilisées dans le cadre de la restauration écologique?", "questionMemorisation": "Complétez l’information suivante : Les zostères permettent la réduction de ___________ dans les zones côtières.", "informationCle": "la force des vagues"},
    {"indice": 17, "question": "Quelles sont les caractéristiques de la végétation poussant dans le Bouclier canadien?", "questionMemorisation": "Nommez une essence de feuillus spécifique que l’on retrouve dans les forêts boréales du Bouclier canadien.", "informationCle": "Les arbres feuillus comprennent l’érable rouge et l’érable à épis, le bouleau gris et le bouleau à papier, le peuplier faux-tremble, le frêne noir et le peuplier baumier"},
    {"indice": 18, "question": "Quelles sont les caractéristiques distinctives entre les deux espèces de rhinocéros africains, soit entre le rhinocéros blanc (Ceratotherium simum) et le rhinocéros noir (Diceros bicornis)?", "questionMemorisation": "Dans quelle zone de l’Afrique peut-on retrouver le rhinocéros blanc?", "informationCle": "Afrique du Sud"},
    {"indice": 19, "question": "Qu’est-ce que le mycélium et quelles sont ses fonctions chez les plantes?", "questionMemorisation": "Nommez une fonction essentielle du mycélium.", "informationCle": "Exploration, décomposition, absorption de nutriments, puit/cycle du carbone, bio-protection"},
    {"indice": 20, "question": "Quelles sont les différences entre le sapin et l’épinette?", "questionMemorisation": "Nommez une caractéristique spécifique des cônes produits par les épinettes par rapport aux cônes produits par les sapins.", "informationCle": "Ils pointent vers le bas, sont souvent au sol"},
    {"indice": 21, "question": "Comment apparaissent les aurores polaires et pourquoi leur coloration varie-t-elle?", "questionMemorisation": "Quel est le phénomène astronomique provenant de l’espace à l’origine d’une aurore polaire?", "informationCle": "Vent solaire"},
    {"indice": 22, "question": "Décrivez ce qui caractérise le genre littéraire du haïku.", "questionMemorisation": "Combien de syllabes contient le 2e vers d’un haiku?", "informationCle": "7 syllabes"},
    {"indice": 23, "question": "Comment le personnage principal du livre Le Comte de Monte-Cristo obtient-il ses richesses, et qu’accomplira-t-il avec sa fortune?", "questionMemorisation": "De qui Edmond Dantès reçoit-il sa fortune lui permettant de devenir le Comte de Monte-Cristo?", "informationCle": "L’abbé Faria"},
    {"indice": 24, "question": "Qui est Oscar Wilde et quels ont été les événements décisifs l’ayant poussé à s’exiler de l’Angleterre?", "questionMemorisation": "Dans quel pays s’est exilé Oscar Wilde?", "informationCle": "France"},
    {"indice": 25, "question": "Décrivez la scène dépeinte dans L’Incrédulité de saint Thomas du Caravage.", "questionMemorisation": "Qu’est-ce que le doigt de saint Thomas touche dans la peinture L’Incrédulité de saint Thomas du Caravage?", "informationCle": "L’abdomen/Flanc de Jésus"},
    {"indice": 26, "question": "Qu’est-ce que la Pax Mongolica et quel a été son impact sur le commerce entre les différentes sociétés de l’Eurasie?", "questionMemorisation": "Quelle route a été revitalisée lors de la Pax Mongolica?", "informationCle": "Route de la soie"},
    {"indice": 27, "question": "Qui est Simone Veil et quel a été son apport en tant que ministre de la Santé?", "questionMemorisation": "Que dépénalise la Loi Veil, préparée par Simone Veil en tant que ministre de la Santé?", "informationCle": "Avortement, IVG"},
    {"indice": 28, "question": "Quels pays s’opposaient dans la Guerre de Sept Ans et quelles ont été les répercussions de la fin de cette guerre sur l’Empire français en Amérique et en Europe?", "questionMemorisation": "Qui est sorti victorieux de la Guerre de Sept Ans?", "informationCle": "Grande-Bretagne, Prusse"},
    {"indice": 29, "question": "Qu’est-ce qu’El Niño et quel est son impact sur les côtes du Pacifique?", "questionMemorisation": "Dans quelle partie de l’océan Pacifique la température de l’eau est-elle anormalement élevée lors du phénomène El Niño?", "informationCle": "Partie Est de l’océan Pacifique Sud, partie Sud-Est"},
    {"indice": 30, "question": "Résumez l’histoire légendaire de Spartacus le gladiateur.", "questionMemorisation": "Qui, finalement, vaincu Spartacus et écrasa sa rébellion d’esclaves?", "informationCle": "Crassus"},
    {"indice": 31, "question": "Décrivez l’histoire racontée dans le film Bienvenue à Gattaca de Andrew Niccol.", "questionMemorisation": "Quel est le prénom du personnage principal du film Bienvenue à Gattaca?", "informationCle": "Vincent"},
    {"indice": 32, "question": "Quelles sont, selon l’UNESCO, les valeurs universelles exceptionnelles qui font du Vieux-Québec un site protégé?", "questionMemorisation": "Nommez un élément du Vieux-Québec qui lui donne sa valeur exceptionnelle selon l’UNESCO.", "informationCle": "Intégrité, authenticité, bien préservé, étape importante de la colonisation, ville coloniale fortifiée, centre historique, taille suffisante, entretient, paysage urbain authentique, etc."},
    {"indice": 33, "question": "Qu’est-ce que le Conseil de sécurité de l’ONU, quels pays y siègent et quels sont ses pouvoirs?", "questionMemorisation": "Nommez un membre permanent du Conseil de sécurité de l’ONU, autre que les États-Unis.", "informationCle": "Chine, Russie, France, Royaume-Uni"},
    {"indice": 34, "question": "Expliquez comment se forme une tornade et quels sont les facteurs climatiques qui contribuent à leur formation?", "questionMemorisation": "Nommez un facteur climatique favorisant l’apparition de tornades.", "informationCle": "Instabilité atmosphérique, cisaillement du vent, présence d’un front météorologique, humidité élevée, températures élevées au sol, présence d’un orage supercellulaire, forcing dynamique"},
    {"indice": 35, "question": "Qui est Banksy et pourquoi est-il reconnu?", "questionMemorisation": "Nommez un thème des œuvres de Banksy.", "informationCle": "Anticapitalisme, antimilitarisme, antisystème, critique sociale et/ou politique, culture populaire"},
    {"indice": 36, "question": "Quels sont les types de nuages catégorisés selon leur hauteur et quelles conditions météorologiques peuvent-ils indiquer?", "questionMemorisation": "Comment se nomme la catégorie de nuages situés le plus en hauteur?", "informationCle": "Cirrus"},
    {"indice": 37, "question": "Quel est le plus grand désert froid du monde et quelles sont ses caractéristiques géographiques principales (faune et flore, climat, position géographique)?", "questionMemorisation": "Quel est le type de climat présent dans le désert de l’Antarctique?", "informationCle": "Climat polaire"},
    {"indice": 38, "question": "Quelles sont les étapes de la formation d’une image sur la rétine?", "questionMemorisation": "Quel est l’organe qui contribue à focaliser les rayons lumineux dans l’œil [sur la rétine] et qui permet une bonne vision de près et de loin en se contractant ou dilatant?", "informationCle": "Le cristallin"},
    {"indice": 39, "question": "Qu’est-ce que la paréidolie visuelle et qu’est-ce qui la cause?", "questionMemorisation": "Nommez une cause de la paréidolie visuelle.", "informationCle": "Dysfonctionnement cérébral, lésion au lobe temporal, évolution/survie"}
    // {"indice": 40, "question": "Qu’est-ce que la Pax Mongolica et quel a été son impact sur le commerce entre les différentes sociétés de l’Eurasie?", "questionMemorisation": "Quelle route a été revitalisée lors de la Pax Mongolica?", "informationCle": "Route de la soie"}
];


/*var questions = [
    {"indice": 1, "question": "Quels sont les trois types de roches et comment se forment-elles?", "questionMemorisation": "Quel est le type de roches formées à partir de lave ou de magma solidifié?"},
    {"indice": 2, "question": "Quelles sont les étapes d’une éruption volcanique?", "questionMemorisation": "Nommez une étape de l’éruption volcanique qui précède l’étape de l’éruption"},
    {"indice": 3, "question": "Expliquez le principe de la photosynthèse et comment les plantes utilisent la lumière pour produire de l’énergie.", "questionMemorisation": "Question3Memo"},
    {"indice": 4, "question": "Expliquez le phénomène d’apparition d’un mirage supérieur et d’un mirage inférieur. ", "questionMemorisation": "Question4Memo"},
    {"indice": 5, "question": "Question5", "questionMemorisation": "Question5Memo"},
    {"indice": 6, "question": "Question6", "questionMemorisation": "Question6Memo"},
    {"indice": 7, "question": "Question7", "questionMemorisation": "Question7Memo"},
    {"indice": 8, "question": "Question8", "questionMemorisation": "Question8Memo"},
    {"indice": 9, "question": "Question9", "questionMemorisation": "Question9Memo"},
    {"indice": 10, "question": "Question10", "questionMemorisation": "Question10Memo"},
    {"indice": 11, "question": "Question11", "questionMemorisation": "Question11Memo"},
    {"indice": 12, "question": "Question12", "questionMemorisation": "Question12Memo"},
    {"indice": 13, "question": "Question13", "questionMemorisation": "Question13Memo"},
    {"indice": 14, "question": "Question14", "questionMemorisation": "Question14Memo"},
    {"indice": 15, "question": "Question15", "questionMemorisation": "Question15Memo"},
    {"indice": 16, "question": "Question16", "questionMemorisation": "Question16Memo"},
    {"indice": 17, "question": "Question17", "questionMemorisation": "Question17Memo"},
    {"indice": 18, "question": "Question18", "questionMemorisation": "Question18Memo"},
    {"indice": 19, "question": "Question19", "questionMemorisation": "Question19Memo"},
    {"indice": 20, "question": "Question20", "questionMemorisation": "Question20Memo"},
    {"indice": 21, "question": "Question21", "questionMemorisation": "Question21Memo"},
    {"indice": 22, "question": "Question22", "questionMemorisation": "Question22Memo"},
    {"indice": 23, "question": "Question23", "questionMemorisation": "Question23Memo"},
    {"indice": 24, "question": "Question24", "questionMemorisation": "Question24Memo"},
    {"indice": 25, "question": "Question25", "questionMemorisation": "Question25Memo"},
    {"indice": 26, "question": "Question26", "questionMemorisation": "Question26Memo"},
    {"indice": 27, "question": "Question27", "questionMemorisation": "Question27Memo"},
    {"indice": 28, "question": "Question28", "questionMemorisation": "Question28Memo"},
    {"indice": 29, "question": "Question29", "questionMemorisation": "Question29Memo"},
    {"indice": 30, "question": "Question30", "questionMemorisation": "Question30Memo"},
    {"indice": 31, "question": "Question31", "questionMemorisation": "Question31Memo"},
    {"indice": 32, "question": "Question32", "questionMemorisation": "Question32Memo"},
    {"indice": 33, "question": "Question33", "questionMemorisation": "Question33Memo"},
    {"indice": 34, "question": "Question34", "questionMemorisation": "Question34Memo"},
    {"indice": 35, "question": "Question35", "questionMemorisation": "Question35Memo"},
    {"indice": 36, "question": "Question36", "questionMemorisation": "Question36Memo"},
    {"indice": 37, "question": "Question37", "questionMemorisation": "Question37Memo"},
    {"indice": 38, "question": "Question38", "questionMemorisation": "Question38Memo"},
    {"indice": 39, "question": "Question39", "questionMemorisation": "Question39Memo"},
    {"indice": 40, "question": "Question40", "questionMemorisation": "Question40Memo"},
    {"indice": 41, "question": "Question41", "questionMemorisation": "Question41Memo"},
    {"indice": 42, "question": "Question42", "questionMemorisation": "Question42Memo"},
    {"indice": 43, "question": "Question43", "questionMemorisation": "Question43Memo"},
    {"indice": 44, "question": "Question44", "questionMemorisation": "Question44Memo"},
    {"indice": 45, "question": "Question45", "questionMemorisation": "Question45Memo"},
    {"indice": 46, "question": "Question46", "questionMemorisation": "Question46Memo"},
    {"indice": 47, "question": "Question47", "questionMemorisation": "Question47Memo"},
    {"indice": 48, "question": "Question48", "questionMemorisation": "Question48Memo"},
    {"indice": 49, "question": "Question49", "questionMemorisation": "Question49Memo"},
    {"indice": 50, "question": "Question50", "questionMemorisation": "Question50Memo"}
];*/